version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodatabase
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: spring_boot_mongo_app
    restart : always
    ports:
      - "27017:27017"
  api_service:
    build: src/main/java
    restart: always
    ports:
      - 8099:8099
    depends_on:
      - mongodatabase
